spring.jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/sns1
  username: mh
  password: Kmh0326!
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: secret-key-sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

#spring.redis.url: localhost:6379
spring.redis:
    host: localhost
    port: 6379


spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="wnrzezzy" password="fJpo5evalyJnfw5IwoYvkoyGhT8PwVoa";

    consumer:
      properties:
        spring.json.trusted.packages: "*"
      bootstrap-servers: moped-01.srvs.cloudkafka.com:9094, moped-02.srvs.cloudkafka.com:9094, moped-03.srvs.cloudkafka.com:9094
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: moped-01.srvs.cloudkafka.com:9094, moped-02.srvs.cloudkafka.com:9094, moped-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: false
    topic:
      alarm: wnrzezzy-alarm
