spring.jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/sns1
  username: uals
  password: Abcd123@
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis.url: localhost:6379

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="wnrzezzy" password="fJpo5evalyJnfw5IwoYvkoyGhT8PwVoa";
    consumer:
      properties.spring.json.trusted.packages: "*" "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: notification
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: "false" "false"
    topic:
      alarm: wnrzezzy-alarm
