spring:
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/sns1
  username: uals
  password: Abcd123@
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000